# docker-compose.yml

version: '3.8'

services:
  mm-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env   # Reference the .env file to load environment variables
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
